# -*- coding: utf-8 -*-
"""Mynavi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_o48RBWphDDXXNc0ztbJ2VHEyIBakD-
"""

from google.colab import auth
from oauth2client.client import GoogleCredentials
import gspread
import json
import time
import random
import datetime
import re#正規表現
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException


# 認証処理
auth.authenticate_user()
gc = gspread.authorize(GoogleCredentials.get_application_default())

# 'SpreadsheetSample'というスプレッドシートの先頭ワークシートをオープン
worksheet = gc.open('Mynavi').get_worksheet(0)

#
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',options=options)


All_number = [652,893,2,278]


for index, item in enumerate(All_number):
  
  index = index + 1
  urls = 'https://www.residentnavi.com/hospitals/' + str(item) + '/early'
  urlss = 'https://www.residentnavi.com/hospitals/' + str(item)
  time.sleep(random.uniform(1,2))
  driver.get(urls)
  
  #if
  #driver.find_element_by_xpath("//*[@id='main']/div/h2").text ==  

  #欲しい情報を取得
  Name = driver.find_element_by_xpath("//*[@id='content_title_set']/div/div[1]/div[2]/h2")
  worksheet.update_cell(index+1,1,Name.text)
  try:
    Money = driver.find_element_by_xpath("//*[@id='main']/div/div[1]/div[1]/div[3]/div[1]/div[1]/table/tbody/tr[3]/td")
  except NoSuchElementException:
    Money = driver.find_element_by_xpath("//*[@id='main']/div/div[1]/div[1]/div[4]/div[1]/div[1]/table/tbody/tr[3]/td")  
  worksheet.update_cell(index+1,2,Money.text)
  driver.get(urlss)#1ページ目読み込み  
  PlaceR = driver.find_element_by_xpath("//*[@id='main']/div/div[1]/div[1]/div[2]/div[1]/table/tbody/tr/td")
  Place = re.sub(r'大きな地図を見る',"", PlaceR.text)
  worksheet.update_cell(index+1,3,Place) 
  worksheet.update_cell(index+1,4,str(item))
  SaiyouN = driver.find_element_by_xpath("//*[@id='main']/div/div[1]/div[1]/div[7]/table/tbody/tr[2]/td/text()[2]")
  worksheet.update_cell(index+1,5,SaiyouN)
  JyukenN = driver.find_element_by_xpath("//*[@id='main']/div/div[1]/div[1]/div[7]/table/tbody/tr[3]/td/text")
  worksheet.update_cell(index+1,6,JyukenN)
  
#ブラウザを閉じる
time.sleep(random.uniform(0,1))
driver.quit()

# -*- coding: utf-8 -*-
 
import re
 
# 対象の文字列
text = "abc123def456efg"
 
# 連続した小文字のアルファベットを置換
result = re.sub(r'[a-z]+', "0", text)
 
print (result)

from google.colab import auth
from oauth2client.client import GoogleCredentials
import gspread
import json
import time
import random
import datetime
import re#正規表現
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException


# 認証処理
auth.authenticate_user()
gc = gspread.authorize(GoogleCredentials.get_application_default())

# 'SpreadsheetSample'というスプレッドシートの先頭ワークシートをオープン
worksheet = gc.open('Mynavi').get_worksheet(0)

#
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',options=options)

#All_number = [652,893,2,278]

All_number = []         
for num in range(5):
    num = num + 100
    All_number.append(num)
    
    
for index, item in enumerate(All_number):  

  urls = 'https://www.residentnavi.com/hospitals/' + str(item) + '/early'

  time.sleep(random.uniform(0,1))
  driver.get(urls)
  try:#404ページ
    PP = driver.find_element_by_xpath("//*[@id='main']/div/h2")
    continue#処理スキップ
  except NoSuchElementException:
    print(index)
  print(item)
  #worksheet.update_cell(item,6,JyukenN)